# PATH TO SHARED TF-IDF VECTORIZER
TFIDF_PATH = r"C:\FAKE NEWS DETECTION\MODEL\VECTORIZER\TFIDF_VECTORIZER.pkl"

# DICTIONARY OF MODEL NAMES (USED IN DROPDOWN) MAPPED TO THEIR RESPECTIVE FILE PATHS
MODEL_PATHS = {
    "LOGISTIC": r"C:\FAKE NEWS DETECTION\MODEL\MODELS\ML\LOGISTIC_TFIDF.pkl",
    "LSTM": r"C:\FAKE NEWS DETECTION\MODEL\MODELS\DL\LSTM_MODEL.h5",
    "CNN": r"C:\FAKE NEWS DETECTION\MODEL\MODELS\DL\CNN_MODEL.h5",
    "DNN": r"C:\FAKE NEWS DETECTION\MODEL\MODELS\DL\DNN_MODEL.h5",
    "NAIVE_BAYES": r"C:\FAKE NEWS DETECTION\MODEL\MODELS\ML\NAIVE_BAYES_TFIDF.pkl",
    "RANDOM_FOREST": r"C:\FAKE NEWS DETECTION\MODEL\MODELS\ML\RANDOM_FOREST_TFIDF.pkl",
}
