# ABOSLUTE FILE PATHS TO SAVED MODEL AND VECTORIZER
MODEL_PATH = r"C:\FAKE NEWS DETECTION\MODEL\MODELS\ML\LOGISTIC_TFIDF.pkl"
TFIDF_PATH = r"C:\FAKE NEWS DETECTION\MODEL\VECTORIZER\TFIDF_VECTORIZER.pkl"
  