from fastapi import FastAPI                         # IMPORTING THE MAIN FASTAPI CLASS TO CREATE THE API APP INSTANCE
from fastapi.middleware.cors import CORSMiddleware  # IMPORTING CORS MIDDLEWARE TO HANDLE CROSS-ORIGIN REQUESTS
from routers.PREDICTION_ROUTER import router as prediction_router  # IMPORTING THE PREDICTION ROUTER (HANDLES FAKE NEWS PREDICTION)
from routers.HEALTH_ROUTER import router as health_router          # IMPORTING THE HEALTH ROUTER (HANDLES API STATUS CHECK)
from utils.LOGGER import logger                     # IMPORTING THE LOGGER FOR LOGGING INFORMATION AND ERRORS

# CREATING AN INSTANCE OF THE FASTAPI APP
# HERE, THE FASTAPI APP INSTANCE IS INSTANTIATED WITH THE TITLE "FAKE NEWS DETECTION API" AND VERSION "1.0"
app = FastAPI(title="FAKE NEWS DETECTION API", version="1.0")  

# ENABLE CORS FOR FRONTEND INTEGRATION
app.add_middleware(
    CORSMiddleware,          # ADDING CORS MIDDLEWARE TO ALLOW CROSS-ORIGIN RESOURCE SHARING
    allow_origins=["*"],     # ALLOWS ALL DOMAINS TO MAKE REQUESTS TO THE API (CHANGE THIS IN PRODUCTION)
    allow_credentials=True,  # ALLOWS COOKIES AND CREDENTIALS TO BE SENT WITH REQUESTS
    allow_methods=["*"],     # ALLOWS ALL HTTP METHODS (GET, POST, PUT, DELETE, ETC.)
    allow_headers=["*"],     # ALLOWS ALL HEADERS TO BE SENT WITH THE REQUEST
)

# INCLUDE ROUTERS (THIS LINKS THE ROUTERS TO THE FASTAPI APP)
app.include_router(prediction_router, prefix="/api")  # INCLUDES THE PREDICTION ROUTER UNDER "/api" PREFIX
app.include_router(health_router, prefix="/api")      # INCLUDES THE HEALTH ROUTER UNDER "/api" PREFIX

logger.info("API INITIALIZED WITH TITLE: 'FAKE NEWS DETECTION API' AND VERSION: '1.0'")  # LOGGING THAT THE API HAS BEEN INITIALIZED WITH THE SPECIFIED TITLE AND VERSION