from fastapi import FastAPI                         # IMPORTING THE MAIN FASTAPI CLASS TO CREATE THE API APP INSTANCE
from fastapi.middleware.cors import CORSMiddleware  # IMPORTING CORS MIDDLEWARE TO HANDLE CROSS-ORIGIN REQUESTS
from ROUTER.PREDICTION_ROUTER import router as prediction_router  # IMPORTING THE PREDICTION ROUTER (HANDLES FAKE NEWS PREDICTION)
from ROUTER.HEALTH_ROUTER import router as health_router          # IMPORTING THE HEALTH ROUTER (HANDLES API STATUS CHECK)
from ROUTER.FEEDBACK_ROUTER import router as feedback_router      # IMPORTING THE FEEDBACK ROUTER (HANDLES USER FEEDBACK)
from UTILS.LOGGER import logger                     # IMPORTING THE LOGGER FOR LOGGING INFORMATION AND ERRORS

# CREATING FASTAPI APPLICATION INSTANCE WITH CUSTOM TITLE AND VERSION
app = FastAPI(
    title="FAKE NEWS DETECTION API",  # SETTING THE API TITLE
    version="1.0"                     # SETTING THE API VERSION
)

# ENABLE CORS FOR FRONTEND INTEGRATION
app.add_middleware(
    CORSMiddleware,          # ADDING CORS MIDDLEWARE TO ALLOW CROSS-ORIGIN RESOURCE SHARING
    allow_origins=["*"],     # ALLOWS ALL DOMAINS TO MAKE REQUESTS TO THE API (CHANGE THIS IN PRODUCTION)
    allow_credentials=True,  # ALLOWS COOKIES AND CREDENTIALS TO BE SENT WITH REQUESTS
    allow_methods=["*"],     # ALLOWS ALL HTTP METHODS (GET, POST, PUT, DELETE, ETC.)
    allow_headers=["*"],     # ALLOWS ALL HEADERS TO BE SENT WITH THE REQUEST
)

# INCLUDE ROUTERS (THIS LINKS THE ROUTERS TO THE FASTAPI APP)
app.include_router(prediction_router, prefix="/api")  # INCLUDES THE PREDICTION ROUTER UNDER "/api" PREFIX
app.include_router(health_router, prefix="/api")      # INCLUDES THE HEALTH ROUTER UNDER "/api" PREFIX
app.include_router(feedback_router, prefix="/api")    # INCLUDES THE FEEDBACK ROUTER UNDER "/api" PREFIX

# LOGGING SUCCESSFUL INITIALIZATION OF THE API
logger.info("API INITIALIZED WITH TITLE: 'FAKE NEWS DETECTION API' AND VERSION: '1.0'")

# DEFINING THE ROOT ENDPOINT "/" TO RETURN A SIMPLE STATUS MESSAGE
@app.get("/")
def read_root():
    # THIS ENDPOINT WILL RESPOND TO GET REQUESTS AT "http://127.0.0.1:8000/"
    return {"message": "FAKE NEWS DETECTION API IS RUNNING!"}  # RETURNING STATUS MESSAGE IN JSON FORMAT
